version: "3"
services:
  database:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "/home/data/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=p0stgr@s
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=k@ycl0ck

  keycloak:
    image: dpranjic/keycloak:21.0.2_phone-2.3.4-snapshot
    container_name: keycloak-test
    #    restart: always
    ports:
      - 8765:8080
    command:
      - start-dev --spi-phone-default-service=dummy --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      #KC_PROXY: edge
      DB_VENDOR: mariadb
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: k@ycl0ck
      DB_PORT: 3306
    links:
      - database:database
    depends_on:
      - database
    volumes:
      - ./:/opt/keycloak/data/import

  # healthcheck:
  #   image: curlimages/curl:latest
  #   command:
  #     - "sh"
  #     - "-c"
  #     - >
  #       while true; do
  #         sleep 3600;
  #       done
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://keycloak:8080/health"]
  #     interval: 10s
  #     timeout: 60s
  #     retries: 5
  #   depends_on:
  #     - keycloak
  #   links:
  #     - keycloak:keycloak
